version: "3.8"

services: 
  postgres: 
    container_name: clean-nest-templete
    # For prodution is recomendly use bitnami images
    image: postgres
    ports: 
      - 5432:5432
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: clean-nest-template
      PGDATA: /data/postgres
    volumes: 
      - ./database/pg:/data/postgres